version: '2'
services:
  web_dev:
    container_name: edgecreator_web_dev
    build: .
    ports:
     - "8003:80"
     - "8446:443"
    volumes:
     - .:/var/www/html
     - /var/www/html/DucksManager/edges:/var/www/html/edges
networks:
  default:
    external:
      name: dm_network
