version: '2'
services:
  web:
    container_name: edgecreator_web
    build: .
    ports:
     - "8002:80"
    volumes:
     - .:/var/www/html
     - /var/www/html/DucksManager/edges:/var/www/html/edges
networks:
  default:
    external:
      name: dm_network
