version: '2'
services:
  web:
    build: .
    ports:
     - "8001:80"
    volumes:
     - .:/var/www/html/EdgeCreator
     - ../DucksManager/images:/var/www/html/DucksManager/images
     - ../DucksManager/edges:/var/www/html/DucksManager/edges
networks:
  default:
    external:
      name: dm_network
